version: '3.8'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
    networks:
      - cloud-network
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
    networks:
      - cloud-network
    depends_on:
      - rabbitmq1
    volumes:
      - ./rabbitmq-entrypoint.sh:/rabbitmq-entrypoint.sh
      - rabbitmq2_data:/var/lib/rabbitmq
    entrypoint: ["bash", "/rabbitmq-entrypoint.sh"]

  mysql-db:
    image: mysql:8.0
    container_name: mysql-transporte
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transporte_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - cloud-network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  cloud-network:
    driver: bridge

volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  mysql_data: