version: '3.8'

services:
  # 1. Nuestro Broker de Mensajería
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # 2. Nuestra Base de Datos
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: transporte_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
      MYSQL_ROOT_PASSWORD: rootpassword

  # 3. Productor 1 (Ubicaciones)
  producer-queue-1:
    build: ./producer-queue-1
    container_name: ms-producer-1
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  # 4. Consumidor 1 (Guarda en MySQL)
  consumer-queue-1:
    build: ./consumer-queue-1
    container_name: ms-consumer-1
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/transporte_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=devuser
      - SPRING_DATASOURCE_PASSWORD=devpassword
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    depends_on:
      - rabbitmq
      - mysql-db

  # 5. Productor 2 (Horarios)
  producer-queue-2:
    build: ./producer-queue-2
    container_name: ms-producer-2
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  # 6. Consumidor 2 (Genera JSON)
  consumer-queue-2:
    build: ./consumer-queue-2
    container_name: ms-consumer-2
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SPRING_RABBITMQ_HOST=rabbitmq
      # Variables para Amazon S3 (AWS SDK las lee automáticamente)
      - AWS_ACCESS_KEY_ID=ASIARJLC45GRP22LD4DL  # Reemplaza con tu Access Key
      - AWS_SECRET_ACCESS_KEY=IpZimhNgSlNKYqhKJC8zUcAECV3YS7LUSjKm7D87
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEHkaCXVzLXdlc3QtMiJGMEQCIASmL0G+YHgeIWN2w1oJOuNW81fL7fPy0OtpkHgs0LdoAiAlnFq1IMz4K0d+lpdXD89qs0rFdvZcctnYz09h+7OstiquAghCEAQaDDA4ODc5MTExNjE5NCIMWT4Ml3Q6kuPq3scwKosCGFDoB+yul1vg2tV5DfSAxJZNXD+2pZ0j5pYVGbA71WzW3LxQ3aJvK+3W8kApQAmReMSKLs1y0Ojn0SbUociO4uaw7MryQPT/wy40nIhce2WrpAzLhHzUuIvxvVFVJ+ehCenlpn5SQgUYETudYJol04wP4Ww75Cq4x+1+IMs2pRhkZCsI1l4ENaXAvfhCmrBnPoeQz6TullIid0Ws4t/htxPDO2PgJ6+PbIpBrX1EqVCqcev3rHx/C71Vmrsa8BerQTSfpSY8wEQ7a8RRsNTGnSCuTAa64fnAbeMEU4OCuLdseiX47mJYE5jHpNaV3J5CclVGK4zOuJYEL8Naa42r8ybgfS9vIdI3FMa+MP/1zswGOp4BZ/CmkoZji1e8K2mE921rsCqfyeYTcpD8CWR2KfVg2BJHtrA9dbvEqBwt76O35hkik8rUAjA6KS4uPCOgkwQH2kphx4iCUTJfUZUAVZODcsM+iZ7k5HYYVxRV5WOjHwh3XI7Jn2vTaFmcxX3TkNby+OIe1McjJdqnxSDTwA/2F91UFXzObZsvMXkmLFGv12ZEuFclhQEIWCbP+rF6PWc=
      - AWS_REGION=us-east-1                    # Pon la región donde creaste tu bucket
      - AWS_S3_BUCKET_NAME=transporte-schedules-cloud-native # El nombre exacto de tu bucket
    depends_on:
      - rabbitmq