server:
  port: 8084

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID}
  secret:
    access:
      key: ${AWS_SECRET_ACCESS_KEY}
  session:
    token: ${AWS_SESSION_TOKEN}
  region: ${AWS_REGION}
  s3:
    bucket:
      name: ${AWS_S3_BUCKET_NAME}